- name: "Configuration de la BDD"
  hosts: bdd
  become: yes
  roles:
    - bdd

- name: "Configuration de l'APP"
  hosts: app
  become: yes
  roles:
    - app

- name: "Test de l'API"
  hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Attendre que l'application soit prête
      wait_for:
        host: "{{ hostvars[groups['app'][0]]['ansible_host'] }}"
        port: "{{ app_port }}"
        timeout: 30

    - name: Effectuer une requête sur l'API
      uri:
        url: "http://{{ hostvars[groups['app'][0]]['ansible_host'] }}:{{ app_port }}"
        return_content: yes
      register: api_response

    - name: Afficher le résultat du test
      debug:
        msg: "La réponse de l'API est : {{ api_response.content }}"