- name: Installer PostgreSQL et dépendances Python pour Ansible
  apt:
    name: ["postgresql", "postgresql-contrib", "python3-psycopg2", "acl"]
    state: present
    update_cache: yes

- name: Créer le groupe cytech_grp
  group:
    name: cytech_grp
    state: present

- name: Créer l'utilisateur (rôle) PostgreSQL
  postgresql_user:
    name: cytech_usr
    password: "{{ db_password }}"
    role_attr_flags: "NOSUPERUSER,CREATEDB"
  become: yes
  become_user: postgres

- name: Créer la base de données cytech
  postgresql_db:
    name: cytech
    owner: cytech_usr
  become: yes
  become_user: postgres

- name: Configurer PostgreSQL pour écouter sur toutes les interfaces
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Autoriser la connexion depuis la VM APP uniquement (pg_hba.conf)
  postgresql_pg_hba:
    dest: "/etc/postgresql/14/main/pg_hba.conf"
    contype: host
    databases: cytech
    users: cytech_usr
    address: "{{ hostvars[groups['app'][0]]['ansible_host'] }}/32"
    method: md5
  become: yes
  become_user: postgres
  notify: restart postgresql

- name: Créer la table 'etudiants' et insérer le prénom
  postgresql_query:
    db: "{{ db_name }}"
    query: |
      CREATE TABLE IF NOT EXISTS etudiants (
          id SERIAL PRIMARY KEY,
          name VARCHAR(50) NOT NULL
      );
      ALTER TABLE etudiants OWNER TO {{ db_user }};
      
      TRUNCATE TABLE etudiants;
      INSERT INTO etudiants (name) VALUES ('Ethan');
  become: yes
  become_user: postgres